# v1.50.0
# Please don't remove the first line. It's used in CI to determine the
# golangci-lint version. See the lint step in .github/workflows/all.yaml
run:
  timeout: 5m

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  # Disable default exclude rules, see `golangci-lint run --help`.
  # When true it disables revive's comment warnings, and we want them enabled.
  exclude-use-default: false

  exclude-rules:
    - path: (.+)_test.go
      linters:
      - wrapcheck
      - funlen
      - cyclop
    - path: k6ext/k6test
      linters:
      - wrapcheck
      - funlen
      - cyclop
    - path: tests
      linters:
      - wrapcheck
      - funlen
      - cyclop

linters:
  disable-all: true
  enable:
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - predeclared
    - prealloc
    - revive
    - staticcheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  gci:
    sections:
      - standard
      - prefix(github.com/grafana/xk6-browser)
      - prefix(go.k6.io)
      - default
  dupl:
    threshold: 400
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/grafana/xk6-browser
  importas:
    alias:
      - pkg: go.k6.io/k6/.*/(\w+)
        alias: k6$1
  nlreturn:
    block-size: 10
  lll:
    maxlength: 120
  gosec:
    config:
      G301: '0755'
      G306: '0644'
