name: Build
on:
  workflow_dispatch:
    inputs:
      xk6_browser_version:
        description: 'The version of the release, it must use the semantic versioning format with the v prefix. It is a development release so it is suggested to append a build metadata (e.g. v0.38.0-dev).'
        required: true
      go_version:
        description: 'Go version for building binaries'
        default: '1.x'
        required: true
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

defaults:
  run:
    shell: bash

env:
  APP_NAME: "xk6-browser"
  DEFAULT_GO_VERSION: "1.19.x"

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      xk6_browser_version: ${{ steps.get_xk6_browser_version.outputs.xk6_browser_version }}
      go_version: ${{ steps.get_go_version.outputs.go_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get the xk6-browser version
        id: get_xk6_browser_version
        run: |
          set -x # Show exactly what commands are executed
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]] && [[ "${{ github.event.inputs.xk6_browser_version }}" != "" ]]; then
            VERSION="${{ github.event.inputs.xk6_browser_version }}"
            echo "Building custom dev build with version '${VERSION}' from manual workflow_dispatch..."
          elif [[ "${GITHUB_REF}" =~ ^refs/tags/v.+$ ]]; then
            VERSION="${GITHUB_REF##*/}"
            echo "Building real version tag '${GITHUB_REF}', parsed '${VERSION}' as the actual version..."
          else
            VERSION="$(git describe --tags --always --long --dirty)"
            echo "Building a non-version ref '${GITHUB_REF}', use '${VERSION}' as the version instead..."
          fi
          echo "VERSION=${VERSION}"
          echo "::set-output name=xk6_browser_version::${VERSION}"
      - name: Get the used Go version
        id: get_go_version
        run: |
          set -x # Show exactly what commands are executed
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]] && [[ "${{ github.event.inputs.go_version }}" != "" ]]; then
            GO_VERSION="${{ github.event.inputs.go_version }}"
            echo "Using custom Go version '${GO_VERSION}' from manual workflow_dispatch..."
          else
            GO_VERSION="${DEFAULT_GO_VERSION}"
            echo "Using the default Go version '${GO_VERSION}'..."
          fi
          echo "GO_VERSION=${GO_VERSION}"
          echo "::set-output name=go_version::${GO_VERSION}"

  build:
    runs-on: ubuntu-latest
    needs: [configure]
    env:
      VERSION: ${{ needs.configure.outputs.xk6_browser_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.configure.outputs.go_version }}
          check-latest: true
      - name: Install xk6
        run: |
          go install go.k6.io/xk6/cmd/xk6@latest
      - name: Install nfpm (dep and rpm package builder)
        run: |
          go install github.com/goreleaser/nfpm/v2/cmd/nfpm@v2.16.0
      - name: Install goversioninfo (.syso file creator)
        run: |
          go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@v1.4.0
      - name: Generate Windows binary metadata (.syso files)
        run: |
          IFS=. read -a version_parts <<< "${VERSION#v}"
          IFS=- read -a version_patch <<< "${version_parts[2]}"

          # Need a blank versioninfo.json for the CLI overrides to work.
          echo '{}' > versioninfo.json
          set -x
          goversioninfo -64 \
            -platform-specific=true \
            -charset="1200" \
            -company="Raintank Inc. d.b.a. Grafana Labs" \
            -copyright="© Raintank Inc. d.b.a. Grafana Labs. Licensed under AGPL." \
            -description="A modern load testing tool, using Go and JavaScript" \
            -icon=packaging/xk6-browser.ico \
            -internal-name="xk6-browser" \
            -original-name="xk6-browser.exe" \
            -product-name="xk6-browser" \
            -translation="0x0409" \
            -ver-major="${version_parts[0]}" \
            -ver-minor="${version_parts[1]}" \
            -ver-patch="${version_patch[0]}" \
            -special-build=$(IFS='-'; echo "${version_patch[*]:1}";) \
            -product-version="${VERSION#v}"

          set +x
          ls -lah | grep -i syso

      - name: Build
        run: |
          go version
          ./build-release.sh "dist" "${VERSION}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: dist/
          retention-days: 7


  package-windows:
    runs-on: windows-2019
    defaults:
      run:
        shell: pwsh
    needs: [configure, build]
    env:
      VERSION: ${{ needs.configure.outputs.xk6_browser_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install pandoc
        uses: crazy-max/ghaction-chocolatey@b6061d587628735be315d74358228b83a7dba9a7
        with:
          args: install -y pandoc
      - name: Install wix tools
        run: |
          curl -Lso wix311-binaries.zip https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
          Expand-Archive -Path .\wix311-binaries.zip -DestinationPath .\wix311\
          echo "$pwd\wix311" | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: dist
      - name: Unzip Windows binary
        run: |
          Expand-Archive -Path ".\dist\xk6-browser-$env:VERSION-windows-amd64.zip" -DestinationPath .\packaging\
          move .\packaging\xk6-browser-$env:VERSION-windows-amd64\xk6-browser.exe .\packaging\
          rmdir .\packaging\xk6-browser-$env:VERSION-windows-amd64\
      - name: Add signtool to PATH
        run: echo "${env:ProgramFiles(x86)}\Windows Kits\10\bin\x64" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Create the MSI package
        run: |
          $env:VERSION = $env:VERSION -replace 'v(\d+\.\d+\.\d+).*','$1'
          pandoc -s -f markdown -t rtf -o packaging\LICENSE.rtf LICENSE.md
          cd .\packaging
          candle.exe -arch x64 "-dVERSION=$env:VERSION" xk6-browser.wxs
          light.exe -ext WixUIExtension xk6-browser.wixobj

      - name: Sign Windows binary and .msi package
        # GH secrets are unavaileble when building from project forks, so this
        # will fail for external PRs, even if we wanted to do it. And we don't.
        # We are only going to sign packages that are built from main or a
        # version tag, or manually triggered dev builds, so we have enough
        # assurance that package signing works, but don't sign every PR build.
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch' }}
        run: |
          # Convert base64 certificate to PFX
          $bytes = [Convert]::FromBase64String("${{ secrets.WIN_SIGN_CERT }}")
          [IO.File]::WriteAllBytes("xk6-browser.pfx", $bytes)

          # Sign the Windows binary
          signtool sign /f xk6-browser.pfx /p "${{ secrets.WIN_SIGN_PASS }}" /tr "http://timestamp.digicert.com" /td sha256 /fd sha256 "packaging\xk6-browser.exe"

          # Sign the MSI package
          signtool sign /f xk6-browser.pfx /p "${{ secrets.WIN_SIGN_PASS }}" /tr "http://timestamp.digicert.com" /td sha256 /fd sha256 "packaging\xk6-browser.msi"

          # Cleanup signing artifacts
          del xk6-browser.pfx

      - name: Rename MSI package
        # To keep it consistent with the other artifacts
        run: move "packaging\xk6-browser.msi" "packaging\xk6-browser-$env:VERSION-windows-amd64.msi"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries-windows
          path: |
            packaging/xk6-browser-*.msi
          retention-days: 7

  publish-github:
    runs-on: ubuntu-latest
    needs: [configure, build, package-windows]
    if: ${{ startsWith(github.ref, 'refs/tags/v') && github.event_name != 'workflow_dispatch' }}
    env:
      VERSION: ${{ needs.configure.outputs.xk6_browser_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: dist
      - name: Download Windows binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries-windows
          path: dist
      - name: Generate checksum file
        run: cd dist && sha256sum * > "xk6-browser-${VERSION}-checksums.txt"
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          assets=()
          for asset in ./dist/*; do
            assets+=("-a" "$asset")
          done
          hub release create "${assets[@]}" -m "$VERSION" -m "$(cat ./release\ notes/${VERSION}.md)" "$VERSION"
